package PrathamCalculator;


/**
* PrathamCalculator/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, 22 October 2014 09:18:35 o'clock PDT
*/

public interface CalcOperations 
{

  //Performs the Calculations:ADD/SUB/MUL/DIV
  int calculate (int _operator, int num1, int num2);

  //The Server EXITS when the Client prompts it to do so
  void shutdown ();
} // interface CalcOperations
